ALTER TABLE Invoice ADD COLUMN paid INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Invoice ADD COLUMN locked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Invoice ADD COLUMN sent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Invoice ADD COLUMN language TEXT NOT NULL DEFAULT 'lt';
ALTER TABLE Invoice ADD COLUMN email TEXT NOT NULL DEFAULT '';
